credentials:
  usernames:
    admin:
      email: admin@example.com
      name: 관리자
      password: $2b$12$vvBdwmDAzdHwlIE3.xjRKOIO2w8oGe6E2wgQjXB.RNr8zKblC5442
    user1:
      email: user1@example.com
      name: 사용자1
      password: $2b$12$AcV9dUS79M7Zrid3IEdgnu97Yg.0NYCFm2duuWdFX/RizDR9eES.i
cookie:
  expiry_days: 30
  key: gboe_tools_secret_key_2024
  name: gboe_tools_cookie 